/**
 * ar.ts — Arabic UI translation dictionary
 *
 * PLACEHOLDER — Will be generated by scripts/generate-translations.ts
 * Run: OPENAI_API_KEY=sk-... npx tsx scripts/generate-translations.ts
 *
 * For now, falls back to English keys.
 */

import type { TranslationDict } from '../i18n';

const ar: TranslationDict = {
  // ── Placeholder — import en.ts keys as fallback ──
  // This file will be fully populated by the ChatGPT translation pipeline.
  // Until then, the i18n engine falls back to the key string itself.
};

export default ar;
