/**
 * fr.ts — French UI translation dictionary
 *
 * PLACEHOLDER — Will be generated by scripts/generate-translations.ts
 * Run: OPENAI_API_KEY=sk-... npx tsx scripts/generate-translations.ts
 *
 * For now, falls back to English keys.
 */

import type { TranslationDict } from '../i18n';

const fr: TranslationDict = {
  // ── Placeholder — will be populated by ChatGPT translation pipeline ──
};

export default fr;
