import { useEffect, useRef, useState } from 'react';

// ── Version key — bump this string to force re-acceptance on legal update ──
const LEGAL_VERSION_KEY = 'roger_legal_v3';

export function hasAcceptedLegal(): boolean {
  return localStorage.getItem(LEGAL_VERSION_KEY) === 'accepted';
}

function acceptLegal() {
  localStorage.setItem(LEGAL_VERSION_KEY, 'accepted');
}

// ─────────────────────────────────────────────────────────────────────────────

const SECTIONS = [
  {
    id: 's1',
    num: '01',
    title: 'Nature of Service',
    body: `ROGER·AI ("the Service") is an AI-powered personal assistant developed and operated by Momencrafts, a company registered in the Kingdom of Saudi Arabia. The Service provides voice-based task management, navigation assistance, and proactive scheduling support.

The Service does not constitute professional, legal, financial, medical, or safety advice of any kind. All outputs generated by the AI are informational in nature and should not be relied upon as a substitute for qualified professional guidance. Momencrafts expressly disclaims any responsibility for decisions made based on AI-generated content.`,
  },
  {
    id: 's2',
    num: '02',
    title: 'Data Collection & Privacy',
    body: `By using the Service, you consent to the collection and processing of the following categories of data: voice recordings and transcriptions, device location and GPS coordinates, contact information (where permission is granted), task and calendar data, and usage analytics.

Contact Information: When you grant contacts access, Roger AI reads only display names from your device address book to improve voice recognition accuracy and enable hands-free messaging. Phone numbers are stored on-device only and are never transmitted to Momencrafts servers. No email addresses, photos, or physical addresses are accessed. You may revoke this access at any time through Settings → Contacts → Disconnect.

All personal data is encrypted at rest and in transit. Momencrafts does not sell, rent, or trade your personal data to third parties. Data is stored on secure cloud infrastructure in compliance with applicable data protection regulations. You may request deletion of your data at any time by contacting support@momencrafts.com.`,
  },
  {
    id: 's3',
    num: '03',
    title: 'AI Limitations & No-Liability',
    body: `ROGER·AI utilises large language models (LLMs) and speech recognition systems that may produce inaccurate, incomplete, or misleading outputs ("hallucinations"). The Service is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind, whether express or implied.

To the maximum extent permitted by applicable law, Momencrafts and its directors, employees, and partners shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service, even if Momencrafts has been advised of the possibility of such damages.`,
  },
  {
    id: 's4',
    num: '04',
    title: 'Driving Safety Warning ⚠',
    body: `CRITICAL SAFETY NOTICE: ROGER·AI includes a hands-free driving mode designed to minimise interaction while operating a vehicle. However, the use of any mobile application while driving may impair your attention and reaction time.

YOU ARE SOLELY RESPONSIBLE FOR OPERATING YOUR VEHICLE SAFELY AND IN COMPLIANCE WITH ALL APPLICABLE TRAFFIC LAWS. Momencrafts shall not be held liable for any accident, injury, property damage, or traffic violation arising from the use of this Service while driving. Always ensure it is safe and legal to interact with your device before doing so.`,
    warn: true,
  },
  {
    id: 's5',
    num: '05',
    title: 'Location & Microphone Access',
    body: `The Service requires access to your device's microphone and location services to function correctly. Microphone access is used exclusively for push-to-talk voice input and is not recorded continuously. Location data is used for navigation, road hazard detection, and contextual AI responses.

You may revoke these permissions at any time through your device settings. Revoking permissions will limit Service functionality. No audio data is retained beyond the duration of an active session without your explicit consent.`,
  },
  {
    id: 's6',
    num: '06',
    title: 'Islamic Mode (Optional Features)',
    body: `ROGER·AI includes an optional Islamic Mode that provides prayer time reminders, Qibla direction, Quranic verses, Hadith, Duas, Hijri calendar, and the 99 Names of Allah — sourced from UmmahAPI.com. This feature is strictly opt-in and disabled by default.

Content provided through Islamic Mode is for informational and educational purposes only. Momencrafts does not claim religious authority and recommends consulting qualified Islamic scholars for matters of religious guidance. Islamic Mode content is not a substitute for personal religious study or scholarly advice.`,
  },
  {
    id: 's7',
    num: '07',
    title: 'Subscription & Payments',
    body: `Access to premium features of the Service is subject to a subscription fee. Subscriptions are billed on a monthly or annual basis and renew automatically unless cancelled at least 24 hours before the end of the current billing period.

Refunds are handled in accordance with the policies of the applicable app store (Google Play / Apple App Store) or payment processor. Momencrafts reserves the right to modify pricing with 30 days' notice. Continued use of the Service after a price change constitutes acceptance of the new pricing.`,
  },
  {
    id: 's8',
    num: '08',
    title: 'Governing Law & Dispute Resolution',
    body: `These Terms and Conditions are governed by and construed in accordance with the laws of the Kingdom of Saudi Arabia. For users in the United Arab Emirates, supplementary consumer protection provisions under UAE Federal Law No. 15 of 2020 on Consumer Protection shall also apply where mandated.

Any dispute arising from the use of the Service shall first be submitted to good-faith mediation. If mediation fails, disputes shall be subject to the exclusive jurisdiction of the competent courts in Riyadh, Kingdom of Saudi Arabia, except where mandatory local law requires otherwise.

For enquiries: legal@momencrafts.com · Momencrafts, Riyadh, Saudi Arabia.`,
  },
];

// ─────────────────────────────────────────────────────────────────────────────

interface Props {
  onAccept: () => void;
}

export default function LegalDisclaimer({ onAccept }: Props) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [canAccept, setCanAccept]     = useState(false);
  const [scrollPct, setScrollPct]     = useState(0);
  const [activeSection, setActiveSection] = useState<string | null>(null);
  const [showDeclineModal, setShowDeclineModal] = useState(false);
  const [declined, setDeclined]       = useState(false);
  const [acceptFlash, setAcceptFlash] = useState(false);
  const sectionRefs = useRef<Record<string, HTMLDivElement | null>>({});

  // ── Scroll tracking ──────────────────────────────────────────────────────
  function onScroll() {
    const el = scrollRef.current;
    if (!el) return;
    const pct = el.scrollTop / (el.scrollHeight - el.clientHeight);
    setScrollPct(pct);
    if (pct >= 0.97 && !canAccept) {
      setCanAccept(true);
      setAcceptFlash(true);
      setTimeout(() => setAcceptFlash(false), 1200);
    }
  }

  // ── Section highlighting via IntersectionObserver ────────────────────────
  useEffect(() => {
    const obs = new IntersectionObserver(
      entries => {
        entries.forEach(e => {
          if (e.isIntersecting) setActiveSection(e.target.id);
        });
      },
      { root: scrollRef.current, threshold: 0.4 }
    );
    Object.values(sectionRefs.current).forEach(el => el && obs.observe(el));
    return () => obs.disconnect();
  }, []);

  function handleAccept() {
    if (!canAccept) return;
    acceptLegal();
    onAccept();
  }

  // ── Tombstone screen ─────────────────────────────────────────────────────
  if (declined) {
    return (
      <div style={outerStyle}>
        <ScanlineOverlay />
        <AmbiGlow />
        <div style={{ position: 'relative', zIndex: 1, textAlign: 'center', padding: 32 }}>
          <div style={{ fontSize: 48, marginBottom: 24 }}>⛔</div>
          <p style={monoStyle(20, '#a84832', '0.28em')}>ACCESS DENIED</p>
          <p style={monoStyle(9, 'rgba(255,255,255,0.3)', '0.2em')}>
            You must accept the Terms &amp; Conditions to use ROGER·AI.<br />
            Close the application or restart to try again.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div style={outerStyle}>
      <ScanlineOverlay />
      <AmbiGlow />

      {/* ── Decline confirmation modal ── */}
      {showDeclineModal && (
        <div style={modalOverlayStyle}>
          <div style={modalBoxStyle}>
            <BracketCorners />
            <p style={monoStyle(10, '#d4a044', '0.22em')}>⚠ CONFIRM DECLINE</p>
            <p style={{ ...bodyTextStyle, marginTop: 12, textAlign: 'center' }}>
              Declining will deny you access to ROGER·AI.<br />
              Are you sure you want to proceed?
            </p>
            <div style={{ display: 'flex', gap: 12, marginTop: 20 }}>
              <button style={btnStyle('ghost')} onClick={() => setShowDeclineModal(false)}>
                CANCEL
              </button>
              <button style={btnStyle('danger')} onClick={() => { setShowDeclineModal(false); setDeclined(true); }}>
                YES, DECLINE
              </button>
            </div>
          </div>
        </div>
      )}

      <div style={{ position: 'relative', zIndex: 1, display: 'flex', flexDirection: 'column', height: '100%', maxWidth: 680, margin: '0 auto', width: '100%' }}>

        {/* ── Header bar ── */}
        <div style={headerBarStyle}>
          <span style={monoStyle(8, 'rgba(212,160,68,0.45)', '0.3em')}>◈ CLASSIFIED</span>
          <span style={monoStyle(9, '#d4a044', '0.25em')}>LEGAL NOTICE · ROGER·AI</span>
          <span style={monoStyle(8, 'rgba(212,160,68,0.45)', '0.3em')}>CLASSIFIED ◈</span>
        </div>

        {/* ── Title block ── */}
        <div style={{ padding: '24px 24px 0', textAlign: 'center', flexShrink: 0 }}>
          <div style={{ fontSize: 32, marginBottom: 10 }}>⚖</div>
          <p style={monoStyle(22, 'rgba(255,255,255,0.92)', '0.28em')}>
            ROGER<span style={{ color: '#d4a044' }}>·</span>AI
          </p>
          <p style={monoStyle(9, '#d4a044', '0.2em')}>TERMS &amp; CONDITIONS OF USE</p>
          <p style={monoStyle(8, 'rgba(255,255,255,0.22)', '0.15em')}>
            VERSION 2.0 · EFFECTIVE 2026-04-25 · MOMENCRAFTS · RIYADH, KSA
          </p>
          <div style={dividerStyle} />
          <p style={{ ...bodyTextStyle, marginBottom: 0 }}>
            Please read these Terms &amp; Conditions carefully before using the Service.
            By tapping <strong>"I ACCEPT"</strong>, you agree to be legally bound by these terms.
          </p>
          <div style={dividerStyle} />
        </div>

        {/* ── Scrollable content ── */}
        <div
          ref={scrollRef}
          onScroll={onScroll}
          style={scrollZoneStyle}
        >
          {SECTIONS.map(sec => (
            <div
              key={sec.id}
              id={sec.id}
              ref={el => { sectionRefs.current[sec.id] = el; }}
              style={sectionStyle(activeSection === sec.id, !!sec.warn)}
            >
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, marginBottom: 10 }}>
                <span style={monoStyle(8, activeSection === sec.id ? '#d4a044' : 'rgba(212,160,68,0.4)', '0.2em')}>
                  §{sec.num}
                </span>
                <span style={monoStyle(11, activeSection === sec.id ? '#d4a044' : 'rgba(255,255,255,0.6)', '0.18em')}>
                  {sec.title.toUpperCase()}
                </span>
                {sec.warn && (
                  <span style={{ marginLeft: 'auto', ...monoStyle(8, '#a84832', '0.12em') }}>
                    ⚠ CRITICAL
                  </span>
                )}
              </div>
              <p style={bodyTextStyle}>{sec.body}</p>
            </div>
          ))}

          {/* Bottom spacer */}
          <div style={{ height: 40 }} />
        </div>

        {/* ── Scroll progress bar ── */}
        <div style={progressTrackStyle}>
          <div style={{ ...progressFillStyle, width: `${Math.min(scrollPct * 100, 100).toFixed(1)}%` }} />
          {!canAccept && (
            <span style={{ ...monoStyle(7, 'rgba(212,160,68,0.5)', '0.18em'), position: 'absolute', right: 8, top: '50%', transform: 'translateY(-50%)' }}>
              ▼ SCROLL TO READ ALL
            </span>
          )}
        </div>

        {/* ── Footer buttons ── */}
        <div style={footerStyle}>
          <button
            id="btn-legal-decline"
            style={btnStyle('ghost')}
            onClick={() => setShowDeclineModal(true)}
          >
            DECLINE
          </button>
          <button
            id="btn-legal-accept"
            style={{
              ...btnStyle('accept'),
              opacity: canAccept ? 1 : 0.3,
              cursor: canAccept ? 'pointer' : 'not-allowed',
              boxShadow: acceptFlash ? '0 0 20px rgba(212,160,68,0.5), 0 0 40px rgba(212,160,68,0.25)' : (canAccept ? '0 0 10px rgba(212,160,68,0.2)' : 'none'),
              transition: 'all 0.4s ease',
            }}
            disabled={!canAccept}
            onClick={handleAccept}
          >
            ✓ I ACCEPT
          </button>
        </div>

        {/* ── Legal footer note ── */}
        <p style={{ ...monoStyle(7, 'rgba(255,255,255,0.12)', '0.12em'), textAlign: 'center', padding: '8px 24px 12px', flexShrink: 0 }}>
          © 2026 MOMENCRAFTS · RIYADH, SAUDI ARABIA · LEGAL@MOMENCRAFTS.COM
        </p>
      </div>

      <style>{`
        @keyframes legalGlow {
          0%, 100% { opacity: 0.6; }
          50% { opacity: 1; }
        }
        @keyframes scrollHint {
          0%, 100% { opacity: 0.5; transform: translateY(0); }
          50% { opacity: 1; transform: translateY(3px); }
        }
      `}</style>
    </div>
  );
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function ScanlineOverlay() {
  return (
    <div style={{
      position: 'absolute', inset: 0, pointerEvents: 'none', zIndex: 0,
      backgroundImage: 'repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0,0,0,0.06) 2px, rgba(0,0,0,0.06) 4px)',
      opacity: 0.6,
    }} />
  );
}

function AmbiGlow() {
  return (
    <>
      <div style={{
        position: 'absolute', top: '10%', left: '50%',
        transform: 'translate(-50%,-50%)',
        width: 600, height: 600, borderRadius: '50%', pointerEvents: 'none',
        background: 'radial-gradient(circle, rgba(212,160,68,0.05) 0%, transparent 65%)',
        animation: 'legalGlow 6s ease-in-out infinite',
      }} />
      <div style={{
        position: 'absolute', bottom: '10%', right: '5%',
        width: 300, height: 300, borderRadius: '50%', pointerEvents: 'none',
        background: 'radial-gradient(circle, rgba(168,72,50,0.04) 0%, transparent 65%)',
      }} />
    </>
  );
}

function BracketCorners() {
  const corner = (style: React.CSSProperties) => (
    <div style={{ position: 'absolute', width: 12, height: 12, ...style }}>
      <div style={{ position: 'absolute', top: 0, left: 0, width: 8, height: 1, background: '#d4a044' }} />
      <div style={{ position: 'absolute', top: 0, left: 0, width: 1, height: 8, background: '#d4a044' }} />
    </div>
  );
  return (
    <>
      {corner({ top: 8, left: 8 })}
      {corner({ top: 8, right: 8, transform: 'scaleX(-1)' })}
      {corner({ bottom: 8, left: 8, transform: 'scaleY(-1)' })}
      {corner({ bottom: 8, right: 8, transform: 'scale(-1)' })}
    </>
  );
}

// ─── Style helpers ────────────────────────────────────────────────────────────

const outerStyle: React.CSSProperties = {
  position: 'fixed', inset: 0, zIndex: 9999,
  background: '#0a0a08',
  display: 'flex', flexDirection: 'column',
  overflow: 'hidden',
};

function monoStyle(size: number, color: string, spacing: string): React.CSSProperties {
  return {
    fontFamily: "'JetBrains Mono', 'Space Mono', monospace",
    fontSize: size,
    color,
    letterSpacing: spacing,
    textTransform: 'uppercase',
    margin: 0,
    lineHeight: 1.5,
  };
}

const bodyTextStyle: React.CSSProperties = {
  fontFamily: "'Inter', system-ui, sans-serif",
  fontSize: 12,
  color: 'rgba(232,229,216,0.72)',
  lineHeight: 1.85,
  margin: 0,
  whiteSpace: 'pre-line',
};

const headerBarStyle: React.CSSProperties = {
  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  padding: '8px 20px',
  borderBottom: '1px solid rgba(212,160,68,0.15)',
  background: 'rgba(212,160,68,0.03)',
  flexShrink: 0,
};

const dividerStyle: React.CSSProperties = {
  height: 1,
  background: 'linear-gradient(90deg, transparent, rgba(212,160,68,0.3), transparent)',
  margin: '16px 0',
};

const scrollZoneStyle: React.CSSProperties = {
  flex: 1,
  overflowY: 'auto',
  padding: '0 24px',
  scrollbarWidth: 'thin',
  scrollbarColor: 'rgba(212,160,68,0.3) transparent',
};

function sectionStyle(active: boolean, warn: boolean): React.CSSProperties {
  return {
    padding: '16px',
    marginBottom: 12,
    border: `1px solid ${warn ? 'rgba(168,72,50,0.3)' : active ? 'rgba(212,160,68,0.3)' : 'rgba(74,82,64,0.2)'}`,
    background: warn
      ? 'rgba(168,72,50,0.04)'
      : active
        ? 'rgba(212,160,68,0.04)'
        : 'rgba(255,255,255,0.01)',
    transition: 'all 0.3s ease',
  };
}

const progressTrackStyle: React.CSSProperties = {
  height: 3,
  background: 'rgba(255,255,255,0.05)',
  position: 'relative',
  flexShrink: 0,
};

const progressFillStyle: React.CSSProperties = {
  height: '100%',
  background: 'linear-gradient(90deg, rgba(212,160,68,0.4), #d4a044)',
  transition: 'width 0.1s linear',
};

const footerStyle: React.CSSProperties = {
  display: 'flex', gap: 12, padding: '14px 24px',
  borderTop: '1px solid rgba(212,160,68,0.12)',
  background: 'rgba(0,0,0,0.3)',
  flexShrink: 0,
};

function btnStyle(variant: 'ghost' | 'accept' | 'danger'): React.CSSProperties {
  const base: React.CSSProperties = {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 10,
    letterSpacing: '0.2em',
    textTransform: 'uppercase',
    padding: '11px 20px',
    border: '1px solid',
    cursor: 'pointer',
    transition: 'all 0.25s ease',
    flex: variant === 'accept' ? 1 : 0,
    background: 'transparent',
  };
  if (variant === 'ghost') return { ...base, color: 'rgba(255,255,255,0.4)', borderColor: 'rgba(255,255,255,0.12)' };
  if (variant === 'danger') return { ...base, color: '#a84832', borderColor: 'rgba(168,72,50,0.4)', background: 'rgba(168,72,50,0.06)' };
  return { ...base, color: '#d4a044', borderColor: 'rgba(212,160,68,0.5)', background: 'rgba(212,160,68,0.08)' };
}

const modalOverlayStyle: React.CSSProperties = {
  position: 'absolute', inset: 0, zIndex: 100,
  background: 'rgba(0,0,0,0.7)',
  display: 'flex', alignItems: 'center', justifyContent: 'center',
  backdropFilter: 'blur(4px)',
};

const modalBoxStyle: React.CSSProperties = {
  position: 'relative',
  background: '#141817',
  border: '1px solid rgba(212,160,68,0.25)',
  padding: '32px 28px',
  maxWidth: 340,
  width: '90%',
  display: 'flex', flexDirection: 'column', alignItems: 'center',
  textAlign: 'center',
};
