// Restores capacitor.settings.gradle after `cap sync` overwrites it with bad relative paths.
// Run: node scripts/fix-gradle.cjs
//
// PROBLEM: `cap sync` generates relative paths like '../../../../../OneDrive/...' which break
// when the project is inside OneDrive or when Gradle resolves from a different working dir.
// FIX: Rewrite the file with absolute paths computed from __dirname at runtime.

const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '..', 'android', 'capacitor.settings.gradle');
const nm   = path.join(__dirname, '..', 'node_modules').replace(/\\/g, '/');

const content = `// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('${nm}/@capacitor/android/capacitor')

include ':capacitor-app'
project(':capacitor-app').projectDir = new File('${nm}/@capacitor/app/android')

include ':capacitor-haptics'
project(':capacitor-haptics').projectDir = new File('${nm}/@capacitor/haptics/android')

include ':capacitor-splash-screen'
project(':capacitor-splash-screen').projectDir = new File('${nm}/@capacitor/splash-screen/android')
`;

fs.writeFileSync(file, content, 'utf8');
console.log('[fix-gradle] capacitor.settings.gradle restored with absolute paths:');
console.log('  node_modules root:', nm);
