// Restores capacitor.settings.gradle after `cap sync` overwrites it with relative paths.
// Run: node scripts/fix-gradle.js
const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '..', 'android', 'capacitor.settings.gradle');
const nodeModulesRoot = path.join(__dirname, '..', 'node_modules').replace(/\\/g, '/');

const content = `// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('${nodeModulesRoot}/@capacitor/android/capacitor')

include ':capacitor-splash-screen'
project(':capacitor-splash-screen').projectDir = new File('${nodeModulesRoot}/@capacitor/splash-screen/android')
`;

fs.writeFileSync(file, content, 'utf8');
console.log('[fix-gradle] capacitor.settings.gradle restored with absolute paths.');
